### ISSUE TITLE
Diff snippet json entries

### ISSUE THREAD

**Issue by shyim** [FriendsOfShopware/shopware-cli#101]
### Actual behaviour

See https://github.com/FriendsOfShopware/actions/issues/10

### Expected behaviour

see https://github.com/FriendsOfShopware/actions/issues/10

### Steps to Reproduce?

see https://github.com/FriendsOfShopware/actions/issues/10

**Comment by tinect** [comment]
We might want to make collecting the snippets dynamic. like any files in any folder names snippets 🤔
