### ISSUE TITLE
changelog formatting in store

### ISSUE THREAD

**Issue by netzperfekt** [FriendsOfShopware/shopware-cli#139]
### Question

when i upload a plugin with _shopware-cli account producer extension upload_ to the store, the markdown in the changelog.md seems to get lost and also the line breaks (see screenshots). 
i don't know if the problem is in the shopware-cli or in the shopware store itself. 
in any case it would be nice if the markdown would be taken over 1:1, like it always worked without problems with the old _FroshPluginUploader_. 
Thanks!
<img width="252" alt="screenshot_432" src="https://user-images.githubusercontent.com/95099795/224387252-e77d4ac5-e9e5-4d65-ade3-533b80310f92.png">
<img width="549" alt="screenshot_431" src="https://user-images.githubusercontent.com/95099795/224387257-1ccea866-c97d-47b5-90fe-df431586fcd8.png">
<img width="545" alt="screenshot_430" src="https://user-images.githubusercontent.com/95099795/224387260-17b684d3-41e2-49e9-a383-63f7a85c9c0c.png">

**Comment by shyim** [comment]
Can you show the HTML difference?

**Comment by netzperfekt** [comment]
thanks @shyim 
is there a special reason why you strip out the "-" and "*" at the beginning of the line? In the old plugin uploader the markdown from the changelog.md was passed directly to the store, which was very practical. or was there a markdown/html converter in the old uploader? 

`versionText = strings.Trim(versionText+line[1:]+"<br>", " ")`

**Comment by netzperfekt** [comment]
@shyim found it - in https://github.com/FriendsOfShopware/FroshPluginUploader/blob/788edf644e67064b3384036818d870de39ffb5ae/src/Components/Generation/ShopwarePlatform/ChangelogReader.php

```
private function renderChangelogAsUl(array $changelog): string
    {
        return '<ul><li>' . implode('</li><li>', $changelog) . '</li></ul>';
    }
```
would you mind implementing this similarly? that would be a big help.
thanks!

**Comment by shyim** [comment]
Now uses normal markdown rendering inside the version stuff

https://github.com/FriendsOfShopware/shopware-cli/pull/142/commits/8eb6951618d82cf3ffdb85051bbe19c90a900036
I just had this reimplemented https://github.com/shopware/platform/blob/trunk/src/Core/Framework/Plugin/Changelog/ChangelogParser.php
