### ISSUE TITLE
Build directory for extension command

### ISSUE THREAD

**Issue by JolanDeNef** [FriendsOfShopware/shopware-cli#155]
### Please describe the feature you would like to see implemented.

When building by using `shopware-cli extension zip ~/pluginpath`, the plugin is built to the current working directory. This results that my root is filled with plugin version, which is not nice.

Ideally, it would be configurable to where it can be built. 

I can think of 2 ways: 
- Automatically build to ~/pluginpath/builds (or output, zip, ...)
- Make it configurable, so I can configure for all my zip files to be build to a chosen dir

**Comment by shyim** [comment]
Maybe a flag `--build-directory` or `--output-directory`

**Comment by flkasper** [comment]
I would suggest `dist` as the folder name, this is also common with other frameworks and tools.
As flag I would suggest `--target-directory`.
Also, I would suggest that the `dist` folder is implemented as a default setting and can be overridden with the flag.

**Comment by shyim** [comment]
I would not change the default directory right now as it would break a lot of CI's
