### ISSUE TITLE
account login with saved old password

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/shopware-cli#16]
### Actual behaviour

When having logged in with a old password and want to call login again, the cli detects saved password. also it detects the password is wrong.

### Expected behaviour

The cli should call relogging when saved password is wrong.
Additionally: remove `shopware-api-client-token.json`, too on every login.

### Steps to Reproduce?

- call `shopware-cli account login`.
- change password of account
- call `shopware-cli account login` again

**Comment by shyim** [comment]
https://github.com/FriendsOfShopware/shopware-cli/commit/857f0478e9a2cbf1eb4460449daca8964170ef46
