### ISSUE TITLE
extension: SW 6.5.x (rc4) webpackJsonp vs. webpackChunk

### ISSUE THREAD

**Issue by rommelfreddy** [FriendsOfShopware/shopware-cli#173]
### Question

when i build/zip the storefront, webpack will built the file for `window.webpackJsonp` storage but in sw 6.5 `self.webpackChunk` storage is used to provide the module. 

File built with SW-CLI:
```
(window.webpackJsonp = window.webpackJsonp || []).push();
```
File built with ./bin/build-storefront.sh
```
(self.webpackChunk = self.webpackChunk || []).push();
```

This will result in that the modules got not injected in the storefront.

i am not sure if this is a bug, or just a misconfiguration. 

i used the latest cli with version 0.1.62

**Comment by shyim** [comment]
How does your composer.json require looks so for `shopware/core`?

**Comment by shyim** [comment]
Due to Webpack changes I guess it's not possible with the default building.

You could take a look into ESBuild with Shopware-cli. https://shyim.me/blog/how-to-build-shopware-extension-assets-faster/

**Comment by shyim** [comment]
I will close this as it has nothing to do with shopware-cli
