### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/shopware-cli#18]
### Actual behaviour

`docker run --rm -v ${PWD}:/app ghcr.io/friendsofshopware/shopware-cli extension prepare /app`

results in Error: `level=fatal msg="prepare zip: PrepareFolderForZipping: exec: \"composer\": executable file not found in $PATH"`

### Expected behaviour

should work

### Steps to Reproduce?

call command in plugin

**Comment by shyim** [comment]
https://github.com/FriendsOfShopware/shopware-cli/commit/244b29c3d53494e0e93e53c2548394df1d1c6f8c
