### ISSUE TITLE
Assets compile for apps on SW6.5 broken

### ISSUE THREAD

**Issue by wannevancamp** [FriendsOfShopware/shopware-cli#181]
### PHP Version

8.1

### Shopware Version

6.5.0.0

### Actual behaviour

Running `shopware-cli extension zip .` for an App will throw an error because the shopware-cli is using node 16 instead of node 18. In the first step shopware-cli clones shopware 6.4 instead of 6.5.

```
git:(main) shopware-cli extension zip .
2023-05-13T08:04:11.386+0200	INFO	Cloning shopware with branch: 6.4 into /var/folders/km/fhgst1b96z51ddqv921dqy5c0000gn/T/extension830748423
```
`Error: error:0308010C:digital envelope routines::unsupported`

### Expected behaviour

A zip with compiled assets for SW6.5 (node 18) will be created

### Steps to Reproduce?

1. Enable asset compilation in `.shopware-extension.yml`
```
build:
  zip:
    assets:
      enabled: true
```
2. Add an App with Javascript
3. Use shopware 6.5
4. run `shopware-cli extension zip .`

See: https://github.com/FriendsOfShopware/shopware-cli/blob/main/extension/asset_platform.go#L351

**Comment by shyim** [comment]
I guess they relate to each other: https://github.com/FriendsOfShopware/shopware-cli/issues/182

**Comment by wannevancamp** [comment]
When it's fixed in the `.shopware-extension.yml` file then https://github.com/FriendsOfShopware/shopware-cli/issues/182 can be closed. Thx!
