### ISSUE TITLE
Make GetShopwareVersionConstraint compatible with Apps manifest.xml

### ISSUE THREAD

**Issue by wannevancamp** [FriendsOfShopware/shopware-cli#182]
### Please describe the feature you would like to see implemented.

Currently, it's not possible to set the minimum ‘Version compatibility’ from within the `.shopware-extension.yml`.
By default, Shopware 6.4 is used. See https://github.com/FriendsOfShopware/shopware-cli/blob/main/extension/app.go#L241
Only plugins can detect the minimum constrained for the composer.json. For Apps we need a constraint in the manifest.xml to fetch the minimum Shopware compatibility. 

Ticket Shopware issue tracker: https://issues.shopware.com/issues/NEXT-26748
Discussed in Slack: https://shopwarecommunity.slack.com/archives/C014X4KR2C8/p1679666193359859

**Comment by wannevancamp** [comment]
https://github.com/FriendsOfShopware/shopware-cli/issues/181 fixes the asset compilation. However, this issue is not fixed yet. The new `shopwareVersionConstraint` in the `.shopware-extension.yml` is not available when uploading a zip because the whole file is added to the `defaultNotAllowedPaths` and so not available in the zipped extension. See: https://github.com/FriendsOfShopware/shopware-cli/blob/main/extension/zip.go#L40

**Comment by shyim** [comment]
AHH yes. and this is related to #191 
https://github.com/FriendsOfShopware/shopware-cli/commit/9dc37c70d872d3b0e6c77cf32e719484fe19925a
