### ISSUE TITLE
Should the extension build command also work with bundles?

### ISSUE THREAD

**Issue by niklaswolf** [FriendsOfShopware/shopware-cli#201]
### Question

I tried to run it for a Shopware-Bundle like so:
```
SHOPWARE_PROJECT_ROOT={PATH_TO_MY_ROOT} shopware-cli extension build PATH_TO_THE_BUNDLE_ROOT
```

Would be nice, as shopware bundles can also extend e.g. the administration :)

**Comment by shyim** [comment]
To build assets I need a Bundle Name + Bundle Path both informations are difficult to obtain for Bundles as I would need to run PHP and actual the Bundle code. And this can get really complicated if the Bundle code requires some environment variables and and...

I would suggest that we use a own composer type `shopware-bundle` with extra field

```json
{
"name": "my-bundle",
"type": "shopware-bundle",
//...
"extra": {
   "bundles": {
    // Relative to bundle directory
     "MyBundle": "src/MyBundle"
   }
}
}
```

And for bundles included in an project we could use only that `extra.bundles`.

**Comment by niklaswolf** [comment]
I see 😊
I don't see any reason against your suggestions, only one thing: I'd rather name the `extra` field also `shopware-bundle` to be a bit more specific and reduce risk of collisions, because `bundle` is quite generic in the symfony environment.

**Comment by shyim** [comment]
Pretty close to finish this. https://github.com/FriendsOfShopware/shopware-cli/pull/227 needs more testing and tests to be fixed

**Comment by shyim** [comment]
https://sw-cli.fos.gg/bundle-support/

**Comment by niklaswolf** [comment]
Thanks for the effort! 😊
