### ISSUE TITLE
Introduce latest:PHP-X.Y Tag

### ISSUE THREAD

**Issue by roman-1983** [FriendsOfShopware/shopware-cli#232]
### Please describe the feature you would like to see implemented.

Would be nice to introduce a specific php-version tag for compatibility of composer packages.

**Comment by shyim** [comment]
We have already:
- 0.3.2-php-8.2
- 0.3.2-php-8.1
- 0.3.2-php-7.4
- 0.3.2-php-7.2

that should be enough 🤔

**Comment by shyim** [comment]
Ahh for latest yes it's right now not there

**Comment by roman-1983** [comment]
Thank you @shyim 🙏
