### ISSUE TITLE
Building static-plugin with SHOPWARE_PROJECT_ROOT should not need shopware/core

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/shopware-cli#246]
### Please describe the feature you would like to see implemented.

When I try to build a plugin in `custom/static-plugins` (project plugin) without set require of shopware/core, `FATAL   cannot get shopware version constraint: require.shopware/core is required` is thrown.

In project, I build by setting SHOPWARE_PROJECT_ROOT, so there might no need to check this in shopware-cli in plugin, is it? 🤔 

https://github.com/FriendsOfShopware/shopware-cli/blob/91c8703d58dbc5277e702cde5fed5b18a354e52a/cmd/extension/extension_build.go#L49

**Comment by shyim** [comment]
is SHOPWARE_PROJECT_ROOT a flex project, or just `shopware/shopware` git repo?

**Comment by tinect** [comment]
flex should be enough.
