### ISSUE TITLE
Bundle assets for multiple major versions

### ISSUE THREAD

**Issue by wannevancamp** [FriendsOfShopware/shopware-cli#251]
### Question

We are building an App which needs to support Shopware 6.4 and 6.5.
The code is the same, only the assets are built differently. sw6.4 (node v16) and sw6.5 (node v18).

We can release 2 different versions of the App in de store each build with a different node version. In this case, we need to set the `Version compatibility` differently for each version. Can this be archieved with the current `.shopware-extension.yml` ?

If this can't be achieved with the current `.shopware-extension.yml`, maybe the following is an option:
Create 2 yml-files and add an option the .shopware-extension.yml file as an optional option to the shopware-cli. See https://github.com/FriendsOfShopware/shopware-cli/blob/a11afa96f613a48500f4ddb36eb95ad62f2a6484/extension/config.go#L104

1. `.shopware-extension-sw64.yml`
```
build:
  shopwareVersionConstraint: '^6.4.8'
```

2. `.shopware-extension-sw65.yml`
```
build:
  shopwareVersionConstraint: '~6.5.0'
```

What is the best approach for this?

**Comment by shyim** [comment]
Does it contain much JS? I would maybe switch to esbuild and https://www.npmjs.com/package/@friendsofshopware/storefront-sdk so you can release the same version for both shopware versions

**Comment by wannevancamp** [comment]
We are using the following JS core classes. Not all of these seem to be available in the [storefront-sdk](https://www.npmjs.com/package/@friendsofshopware/storefront-sdk), so using the SDK doesn't seem like an option. Is that correct? I haven't used the SDK before.

- 'src/helper/dom-access.helper';
- 'src/plugin-system/plugin.manager';
- 'src/plugin-system/plugin.class'
- 'src/plugin/cookie/cookie-configuration.plugin';
- 'src/helper/storage/cookie-storage.helper';
- 'src/helper/dom-access.helper';

> but yes, you can use that constraint field for that purpose.

Is it correct that we currently need 2 different `.shopware-extension.yml` files with each there own `shopwareVersionConstraint`? Of course, we prefer to maintain one version of the App instead of a separate one for each major.
