### ISSUE TITLE
Plugin states in project configuration

### ISSUE THREAD

**Issue by Jnoack331** [FriendsOfShopware/shopware-cli#252]
### Please describe the feature you would like to see implemented.

We currenctly need something that activates/deactivates/updates plugins in a list. I would implement this into the project configuration files using the already created plugin api calls. Any thoughts/issues with this?

**Comment by shyim** [comment]
Sounds good. Feel free to do that :)

**Comment by shyim** [comment]
I am closing this, as the solution is here https://github.com/shopware/deployment-helper/

I would still accept a PR, when you implement it :)
