### ISSUE TITLE
Command "admin-watch" returns "404 Not found" at "http://localhost:8080/admin" on MacOS

### ISSUE THREAD

**Issue by M-arcus** [FriendsOfShopware/shopware-cli#255]
### PHP Version

8.1

### Shopware Version

6.5.6.1

### Actual behaviour

Browser shows "404 Not found" at "http://localhost:8080/admin" on MacOS after executing the command `shopware-cli extension admin-watch . http://127.0.0.1:8000`

The output on the console is:

```
~/PhpstormProjects/adminwatch-test via 🐘 v8.2.12 via ❄️  impure (devenv-shell) $ shopware-cli extension admin-watch . http://127.0.0.1:8000/
2023-11-13T11:17:45.480+0100	INFO	Found extension using Composer: FroshDevelopmentHelper (1.0.2)
2023-11-13T11:17:45.480+0100	INFO	Found extension using Composer: FroshTools (1.2.3)
2023-11-13T11:17:45.480+0100	INFO	Found extension using Composer: MyTestPlugin (1.0.0)
2023-11-13T11:17:45.536+0100	INFO	Admin Watcher started at http://localhost:8080/admin
2023-11-13T11:17:46.683+0100	DEBUG	Got request GET /admin
2023-11-13T11:17:46.702+0100	DEBUG	Served modified admin
```

### Expected behaviour

http://localhost:8080/admin displays the admin page.

This works without an issue on the newest stable Linux Mint version, but fails in Macos.

### Steps to Reproduce?

1. `brew install FriendsOfShopware/tap/shopware-cli`, verify its version: `0.3.12`
2. `shopware-cli project create adminwatch`, choose `6.5.6.1`
3. `cd adminwatch`
4. `composer require devenv`
5. `direnv allow`
6. `devenv up`
7. `bin/console system:install --basic-setup --create-database --force`
8. Access Shopware Admin area, go through setup steps
9. `composer require frosh/development-helper frosh/tools`
10. `bin/console plugin:refresh && bin/console plugin:install -ac FroshDevelopmentHelper FroshTools`
11. `shopware-cli project admin-build`
12. `shopware-cli extension admin-watch . http://127.0.0.1:8000`
13. Click on link in the console

**Comment by scriptibus** [comment]
Didn't try to reproduce, but maybe you have a typo, starting the watcher at port 8000 and checking port 8080?

**Comment by shyim** [comment]
I could reproduced it. The problem is that the URL passed to the admin-watch is wrong.

The URL `http://127.0.0.1:8000`  gives a 404 in the browser when you open it. When you use `http://localhost:8000` instead it works in Browser and in shopware-cli
