### ISSUE TITLE
Pull command is using wrong company

### ISSUE THREAD

**Issue by momocode-de** [FriendsOfShopware/shopware-cli#259]
### PHP Version

8.1

### Actual behaviour

I am using the CLI for the first time and I wanted to download the store info for my plugin. I followed the [Quick Start Guide](https://sw-cli.fos.gg/extension_quick_start/) for this. So I logged in first and then the wrong company was active by default. So I used `shopware-cli account company list` to get the company list and then `shopware-cli account company use <id>` to change the active company. I got the message "Successfully changed your company to ...". But now, if I do `shopware-cli account producer extension info pull .` I'm getting the error "cannot get producer endpoint: this company is not unlocked as producer" because the other company is used.

### Expected behaviour

I expect to use the company I previously switched to.

### Steps to Reproduce?

See "Actual behaviour"

**Comment by momocode-de** [comment]
Sorry, I just saw that I have a relatively old version of shopware-cli (0.2.1). I have integrated the shopware-cli via devenv like described [here](https://sw-cli.fos.gg/install/#devenv). Can I also get a more up-to-date version there?

**Comment by shyim** [comment]
Can you run devenv update

**Comment by momocode-de** [comment]
> Can you run devenv update

Yes, now it's on 0.3.12. Not the newest, but it was working now to download the store infos. Thank you!
