### ISSUE TITLE
Pull command assigns description and installation manual to wrong language and resets zip excludes

### ISSUE THREAD

**Issue by momocode-de** [FriendsOfShopware/shopware-cli#264]
### Actual behaviour

I have a plugin for which I had already downloaded the store information, so the .shopware-extension.yml already exists. If I now execute the pull command again, I have two problems:

1. The languages (DE and EN) for the description and installation manual are reversed. The english text is pulled to the "de" key and the german text is pulled to the "en" key. And yes, I checked again to see if it's correct in the account, and it is.
2. To exclude certain files and paths from the ZIP, I have added them under build.zip.pack.excludes.paths. This configuration is reset again after using the pull command.

Or is it not intended to use the pull command again after it has been used initially? But from my point of view, it is a valid case that you customize something via the account and then want to pull it into your plugin.

I am using version 0.3.12 of the CLI, as devenv does not yet offer the latest version. According to the changelogs, however, the problem has not yet been fixed.

### Expected behaviour

I expect that the description and installation manual are assigned to the correct languages and that the build.zip.pack.excludes.paths configuration is not reset.

### Steps to Reproduce?

See "Actual behaviour"

**Comment by shyim** [comment]
Can you run `devenv update` and check if that shopware-cli version works for you?

**Comment by momocode-de** [comment]
> Can you run `devenv update` and check if that shopware-cli version works for you?

In the "unstable" channel the shopware-cli is only available up to version 0.3.12, see: [https://search.nixos.org/packages?channel=unstable&show=shopware-cli&from=0&size=50&sort=relevance&type=packages&query=shopware-cli](https://search.nixos.org/packages?channel=unstable&show=shopware-cli&from=0&size=50&sort=relevance&type=packages&query=shopware-cli)

So I can't test it in a newer version.
