### ISSUE TITLE
Admin watch doesn't work and does not support npm dependencies

### ISSUE THREAD

**Issue by creinelt** [FriendsOfShopware/shopware-cli#273]
### PHP Version

8.2

### Shopware Version

6.5.7.2

### Plugin Version

0.3.18

### Actual behaviour

Using additional npm dependencies does not work:
![image](https://github.com/FriendsOfShopware/shopware-cli/assets/42065078/931c17eb-e87d-4893-ac9f-6707fe15544a)

The code of my extension does not get loaded or refreshed at all:
![image](https://github.com/FriendsOfShopware/shopware-cli/assets/42065078/aa4181c7-6162-4f49-a92b-274c68df4eca)
![image](https://github.com/FriendsOfShopware/shopware-cli/assets/42065078/c0a059c4-f89c-4aa8-8ae6-6791a1df31ab)

Tested with Dockware Images.

### Expected behaviour

npm dependencies should be supported and the watcher should work with dockware in general.

### Steps to Reproduce?

Create a new container with a dockware image.
Create a test plugin.
Add a npm dependency to your admin extension
run the watcher

**Comment by creinelt** [comment]
I have been able to find out why the watcher generally does not work for my plugin. If the plugin has numbers in the name, it no longer works, this is due to this regular expression:

https://github.com/FriendsOfShopware/shopware-cli/blob/08ec48ea4d66e8f9627dab337b078870c2e57d72/cmd/extension/extension_admin_watch.go#L38C2-L38C83

It should include numbers aswell:
`(?m)/.shopware-cli/([a-z0-9-]+)/(.*)$`

**Comment by shyim** [comment]
AHHH!
