### ISSUE TITLE
Storefront build breaks plugin

### ISSUE THREAD

**Issue by hhoechtl** [FriendsOfShopware/shopware-cli#285]
### Actual behaviour

When the plugin `mediameetsfacebookpixel` is installed, it generates 2 identical js files, one is missing the `m` in the name. 
Therefore the storefront loads the plugin twice and breaks.

![image](https://github.com/FriendsOfShopware/shopware-cli/assets/5076356/b197dd90-2c28-41ae-b816-6febecafe223)

### Expected behaviour

There should be only one built dist js

### Steps to Reproduce?

Install store.shopware.com/mediameetsfacebookpixel and try `shopware-cli project storefront-build`

**Comment by shyim** [comment]
latest shopware-cli version?

**Comment by hhoechtl** [comment]
0.4.4
