### ISSUE TITLE
Blacklist bundles for admin / storefront build

### ISSUE THREAD

**Issue by hhoechtl** [FriendsOfShopware/shopware-cli#286]
### Please describe the feature you would like to see implemented.

When using `shopware-cli project ci` it will build the administration source.
Unfortunately it will build all bundles no matter if they are active or not.
Since SW 6.5 the admin has lazy loading and the modules it tries to load are also the deactivated modules.

Either we must implement a manual blacklist or find a way to manipulate the webpack module loader in the final build.

This is true for e.g. SwagCommercial, as it builds and therefore loads admin js modules from deactivated features, which breaks the administration.

**Comment by shyim** [comment]
You mean ComposerPluginLoader loads all plugins even whey they are not installed and activated in the database? 🤔 
I don't got the problem so far 🤔

**Comment by shyim** [comment]
`project ci` is "smart" enough to understand that plugins bring their pre-build stuff and don't build them. SwagCommercial assets should be never built in your pipeline as they are provided in their zip

**Comment by hhoechtl** [comment]
But the built admin is trying to load those JS modules, which it shouldn't. It doesn't do that, if I build the admin with `bin/build-administration.sh`

**Comment by hhoechtl** [comment]
It's not only about buildling, but the generated module loader for the admin contains modules which should not be active => disabled SwagCommercial features for example.
As far as I understood it, the webpack is reading the `var/plugins.json` to build the module loader and in case of `shopware-cli` it contains too many modules (deactivated ones) which break the admin.

**Comment by shyim** [comment]
I think you refer to the "asset marker" shopware-cli generates for the plugins:
https://github.com/FriendsOfShopware/shopware-cli/blob/main/cmd/project/ci.go#L146C8-L146C8

When that file exists in that plugin, Shopware just loads the JS 🤔 . Can you delete that file for that plugin and check again?

**Comment by shyim** [comment]
So a basic list of asset building exclusions would help you in the `.shopware-project.yml`

```
excludeExtensions:
- Name
```

and these are not considered by shopware-cli to built any assets?

**Comment by hhoechtl** [comment]
Yes
