### ISSUE TITLE
Doc Issue: extension creation in account

### ISSUE THREAD

**Issue by amenk** [FriendsOfShopware/shopware-cli#293]
### PHP Version

-

### Shopware Version

-

### Plugin Version

-

### Actual behaviour

Docs state a wrong command https://sw-cli.fos.gg/extension_quick_start/ un der "Optional: Create the extension in the Account"

Right command: `shopware-cli account producer extension create ImiDiPasswordProtectedPages platform`

### Expected behaviour

Extension is created in the store :-)

### Steps to Reproduce?

shopware-cli extension create ImiDiPasswordProtectedPages platform

**Comment by shyim** [comment]
Do you mind creating a PR?

**Comment by amenk** [comment]
Sure - @shyim I did not find the repo / file :-)

**Comment by shyim** [comment]
They are here :) https://github.com/FriendsOfShopware/shopware-cli/tree/main/wiki/docs
