### ISSUE TITLE
shopware-cli project proxy - matching sales channel

### ISSUE THREAD

**Issue by wannevancamp** [FriendsOfShopware/shopware-cli#315]
### Question

I recently came across the undocumented command `shopware-cli project proxy`.

The following config is set in the env.local.
``` 
APP_URL=http://127.0.0.1:8020
TRUSTED_PROXIES=127.0.0.1,::1
 ```

- Database: sales_channel_domain.url = http://127.0.0.1:8020
- Proxy URL: https://poster-crops-que-pencil.trycloudflare.com/

Result:
```
Unable to find a matching sales channel for the request: "https://poster-crops-que-pencil.trycloudflare.com/". Please make sure the domain mapping is correct.
```

What am I doing wrong?

**Comment by shyim** [comment]
Are you on 6.5 or 6.6?

**Comment by wannevancamp** [comment]
Tested on both 6.5 and 6.6. Both versions gave the same error.

**Comment by shyim** [comment]
Ahhh you need to create a sales channel or add a new domain with the given URL 😅 . It does not auto replace it 😓

**Comment by wannevancamp** [comment]
Aha oké, make sense 😃. I thought it would work the same as ngrok or [expose](https://expose.dev/). With those services you can keep using the local domain
