### ISSUE TITLE
Read folders for screenshots

### ISSUE THREAD

**Issue by digitvision** [FriendsOfShopware/shopware-cli#317]
### Please describe the feature you would like to see implemented.

could you update the shopwae-cli shopware-extension.yml to read a directory for screenshots automatically?!
would be nice if a could set a directory and the priority (= sorting) is set by the file name. this would make this a loooot easier:

<img width="229" alt="Bildschirmfoto 2024-03-05 um 12 33 04" src="https://github.com/FriendsOfShopware/shopware-cli/assets/41727545/b309415d-7249-4895-94ea-c9066b57877e">

**Comment by shyim** [comment]
How do you separate between english language screenshot and german?

**Comment by shyim** [comment]
and first image of the priority will be the preview?

**Comment by digitvision** [comment]
That would make sense, yes
