### ISSUE TITLE
database dump optimize

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/shopware-cli#342]
### Please describe the feature you would like to see implemented.

It might be good, to add the following to the beginning to improve performance:
```
    SET autocommit=0; 
    SET unique_checks=0; 
    SET foreign_key_checks=0;
```

See: https://dev.mysql.com/doc/refman/8.0/en/optimizing-innodb-bulk-data-loading.html

**Comment by shyim** [comment]
I don't know about autocommit. Maybe this blows up the mysql server on bigger data sets, as it never writes it to disk and then everything at once. maybe memory fills up completely or something like that 🤔

**Comment by shyim** [comment]
I would keep it is as it is right now 🤔
