### ISSUE TITLE
shopwareVersionConstraint put max compatibility wrong 

### ISSUE THREAD

**Issue by wannevancamp** [FriendsOfShopware/shopware-cli#357]
### Plugin Version

0.4.41

### Actual behaviour

When publishing apps to the Shopware store the manifest.xml constraint does not work the same way composer handles the constraints.

We have an app which is compatible with all versions higher than 6.4.8.0 and lower than 6.6.0.0. After uploading to the store, the max compatibility is set to 6.6.1.2 which is not allowed. 

**Manifest.xml**
```
build:
  shopwareVersionConstraint: '~6.4.8 || ~6.5.0'
```

![image](https://github.com/FriendsOfShopware/shopware-cli/assets/3399877/70b1fb54-3d3e-412c-bb39-d7e5260b0fe7)

### Expected behaviour

The max compatibility is set to the latest 6.5 version (currently 6.5.8.9)

### Steps to Reproduce?

1. set shopwareVersionConstraint in manifest.xml
2. shopware-cli account producer extension upload ...
3. check max compatibility version in account.shopware.com

**Comment by shyim** [comment]
this should be okay again with the latest release right?

**Comment by wannevancamp** [comment]
Correct, the latest version works correct 👍
