### ISSUE TITLE
CI command does not delete dev composer dependencies inside GitHub Action

### ISSUE THREAD

**Issue by M-arcus** [FriendsOfShopware/shopware-cli#359]
### PHP Version

8.2

### Shopware Version

6.5.8.9

### Plugin Version

-

### Actual behaviour

Deployment with deployer:
`deployer.php` includes a code `runLocally('shopware-cli project ci .');` 
But this does not lead to the dev dependencies being ignored/removed during install.

### Expected behaviour

`composer install` during ci command is executed with `--no-dev`

### Steps to Reproduce?

Execute `shopware-cli project ci .` inside a deployer deployment inside GitHub Action

**Comment by M-arcus** [comment]
Workaround: `--with-dev-dependencies=false`

**Comment by M-arcus** [comment]
https://github.com/FriendsOfShopware/shopware-cli/blob/main/cmd/project/ci.go#L65
Could the cause be the check of `.Changed`? I see no other uses of `.Changed` in the repo, these arguments are usually declared in the `.init` function of each command.

**Comment by shyim** [comment]
yup thats it. i reverted it https://github.com/FriendsOfShopware/shopware-cli/commit/9a534e1683adc98e32c008c4d04771e49c4512d2 we don't need it anyway anymore
