### ISSUE TITLE
Add possibility to pass empty password for MySQL user

### ISSUE THREAD

**Issue by rompwow** [FriendsOfShopware/shopware-cli#369]
### Please describe the feature you would like to see implemented.

I've installed the cli and tried creating a dump file. As the password defaults to "root" and I cannot pass an empty string to the `--password` arg, I cloned the repository and tried editing the file `cmd/project/project_dump.go`.

I replaced the line 30
`password, _ := cmd.Flags().GetString("password")`

with
`password = ""`

I then built the cli, but using the cli still returns the same error:
`FATAL   Error 1698 (28000): Access denied for user 'root'@'localhost'`

I verified that I can indeed connect using `mysql -uroot -hlocalhost` and that works perfectly.

**Comment by shyim** [comment]
Can you do the same

```
mysql -uroot -h127.0.0.1
```
