### ISSUE TITLE
Please migrate to go 1.23

### ISSUE THREAD

**Issue by pkramme** [FriendsOfShopware/shopware-cli#398]
### Please describe the feature you would like to see implemented.

Hello, 

Go 1.23 has been released and features one important change that is interesting to shopware-cli:
> On Linux with pidfd support (generally Linux v5.4+), [Process](https://go.dev/pkg/os#Process)-related functions and methods use pidfd (rather than PID) internally, eliminating potential mistargeting when a PID is reused by the OS. Pidfd support is fully transparent to a user, except for additional process file descriptors that a process may have.
(https://go.dev/doc/go1.23)

This will resolve a problem where the `shopware-cli project worker` command might kill an unrelated process if the previous pid is reused within a very short timeframe. This is not extremely realistic, but especially in low pid counts with low limits (like in some Docker environments) this might happen. 

An update to Go 1.23 might improve this situation.

Thanks!

**Comment by shyim** [comment]
seems only golangci lint fails, https://github.com/FriendsOfShopware/shopware-cli/pull/399

I will fix it later

**Comment by shyim** [comment]
is released already
