### ISSUE TITLE
Completion scripts show shopware-cli instead of shopware

### ISSUE THREAD

**Issue by tinect** [FriendsOfShopware/shopware-cli#4]
### Actual behaviour

the completion script for bash (I assume others too) are based on command `shopware-cli`, but it should be `shopware`

### Expected behaviour

print and use correct command. Use `shopware-cli [command]` or `shopware [command]` all over.

### Steps to Reproduce?

install bash completion script and seeing not having auto-completion

**Comment by shyim** [comment]
fixes it already https://github.com/FriendsOfShopware/shopware-cli/commit/4d58338089af8d420e4bfe9c81d7f3b73047f0f0
