### ISSUE TITLE
Feature: Allow to specify config sync targets

### ISSUE THREAD

**Issue by cloudmaker97** [FriendsOfShopware/shopware-cli#416]
### Please describe the feature you would like to see implemented.

Is there a way to synchronize only mail templates? A command attribute would be awesome to specify the sync targets on my own; when no attribute is given, sync all by default. This would e.g. a good way to put mail templates in VCS and keep them in sync with the shop while development.

I took a quick look into the source code to check if there is something like that already implemented. My Go-Skills are not sufficient to clarify, if this already possible, but in the documentation I can't find anything about this topic, even not in the code.
https://github.com/FriendsOfShopware/shopware-cli/blob/c20cbb8276451060cab4db00a3de0dccf7d225ac/cmd/project/config_sync.go#L38

**Comment by shyim** [comment]
It only pushes when there is data for, so you could delete it from yaml file 🤔

**Comment by cloudmaker97** [comment]
But very inconvenient when you pull to get the latest update from the shop, then you push and forgot to delete parts in the yaml file. I mean, i've built a command wrapper in php to avoid that, but i miss that feature in vanilla shopware-cli.

**Comment by cloudmaker97** [comment]
Thank you so much for this improvement! 👍🏻
