### ISSUE TITLE
project dump panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by Robin-Marquardt** [FriendsOfShopware/shopware-cli#418]
### PHP Version

8.3

### Shopware Version

6.6.6.1

### Plugin Version

0.4.55

### Actual behaviour

MySQL Version: 8.3
Shopware Version: 6.6.6.1
Command:
shopware-cli project dump shopware_xxx --username root --password xxx --host xxx.xxx.xxx.xxx --skip-lock-tables --output dump_manually.sql

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/doutorfinancas/go-mad/generator.service.ReplaceStringWithFakerWhenRequested({{{0x14e7be8, 0xc00042f2c0}}}, {0xc0005a5140, 0x13})
	github.com/doutorfinancas/go-mad@v0.0.0-20240205120830-463c1e9760f0/generator/faker.go:57 +0x572
github.com/doutorfinancas/go-mad/database.(*mySQL).getProperEscapedValue(0xc000222900, 0xc0000da918?, {0xc000136a58?, 0x1?}, {0xc0005bc319?, 0x2?})
	github.com/doutorfinancas/go-mad@v0.0.0-20240205120830-463c1e9760f0/database/mysql.go:415 +0xe6
github.com/doutorfinancas/go-mad/database.(*mySQL).dumpTableData(0xc000222900, {0x14e10a0, 0xc00043a320}, {0xc000136a58, 0x8})
	github.com/doutorfinancas/go-mad@v0.0.0-20240205120830-463c1e9760f0/database/mysql.go:388 +0x6b2
github.com/doutorfinancas/go-mad/database.(*mySQL).dumpData(0xc000222900, {0x14e10a0, 0xc00043a320}, {0xc0002f4000, 0x1463}, {0xc000136a58, 0x8})
	github.com/doutorfinancas/go-mad@v0.0.0-20240205120830-463c1e9760f0/database/mysql.go:279 +0x19a
github.com/doutorfinancas/go-mad/database.(*mySQL).Dump(0xc000222900, {0x14e10a0, 0xc00043a320})
	github.com/doutorfinancas/go-mad@v0.0.0-20240205120830-463c1e9760f0/database/mysql.go:148 +0x645
github.com/FriendsOfShopware/shopware-cli/cmd/project.init.func12(0x1c9d820, {0xc0001613f0, 0x1, 0x12bbc41?})
	github.com/FriendsOfShopware/shopware-cli/cmd/project/project_dump.go:191 +0x1db1
github.com/spf13/cobra.(*Command).execute(0x1c9d820, {0xc000161340, 0xb, 0xb})
	github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0x1c95f60)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.8.1/command.go:1034
github.com/FriendsOfShopware/shopware-cli/cmd.Execute({0x14ea688, 0x1d269e0})
	github.com/FriendsOfShopware/shopware-cli/cmd/root.go:39 +0x169
main.main()
	github.com/FriendsOfShopware/shopware-cli/main.go:10 +0x25

### Expected behaviour

working Database Dump :)

### Steps to Reproduce?

Command: shopware-cli project dump shopware_xxx --username root --password xxx --host xxx.xxx.xxx.xxx --skip-lock-tables --output dump_manually.sql

**Comment by shyim** [comment]
https://github.com/doutorfinancas/go-mad/pull/54

**Comment by m-waes** [comment]
Just adding to this:
if I explicitly add `--anonymize` it works again.

> shopware-cli --version
shopware-cli version 0.4.33

>Shopware 6.5.8.7

**Comment by shyim** [comment]
Can you update shopware-cli it's pretty old 🤔

**Comment by shyim** [comment]
--clean with without --anonymize it works still for me
