### ISSUE TITLE
GitHub release note links are broken (404)

### ISSUE THREAD

**Issue by RafaelKr** [FriendsOfShopware/shopware-cli#438]
The links of the release notes are following this scheme: `https://github.com/FriendsOfShopware/FroshTools/blob/2.4.2/628f9db`

But when opening any of those links I'm taken to a GitHub 404 page.
See: https://github.com/FriendsOfShopware/FroshTools/releases

**Comment by schneider-felix** [comment]
I created a PR #439 that will fix this issue. Sadly existing changelogs will not be touched by this change. I hope I was able to help anyways.
