### ISSUE TITLE
Reading arbitrary JSON files in the Resources/app/administration/src folder causes FATAL error while merging snippets

### ISSUE THREAD

**Issue by jankal** [FriendsOfShopware/shopware-cli#443]
### PHP Version

8.3

### Shopware Version

6.6.8.2

### Plugin Version

dev / 0.4.60

### Actual behaviour

In [`cmd/project/ci.go:338`](https://github.com/FriendsOfShopware/shopware-cli/blob/9e5a40d698ec9137d50a3968963fd079bde4165d/cmd/project/ci.go#L338) to [`cmd/project/ci.go:391`](https://github.com/FriendsOfShopware/shopware-cli/blob/9e5a40d698ec9137d50a3968963fd079bde4165d/cmd/project/ci.go#L391) we read all JSON files from the admin Resources folder and treat them as languages.

We do not verify if those files actually contain snippets but expect them to start with an object as base type thus erroring on a JSON file with an array as it's base data structure.

The error message looks like this:
```
FATAL   json: cannot unmarshal array into Go value of type map[string]interface {}
```

I locally added some debug output after [`cmd/project/ci.go:389`](https://github.com/FriendsOfShopware/shopware-cli/blob/9e5a40d698ec9137d50a3968963fd079bde4165d/cmd/project/ci.go#L389) to figure out which file actually caused the error thus getting to the bottom of this.

### Expected behaviour

When running `shopware-cli project ci .` only actual snippet files should be read from `Resources/app/administration/src` folders in bundles / plugins.

### Steps to Reproduce?

Run `shopware-cli project ci .` in a project where a JSON file with just an array is put into a plugins `Resources/app/administration/src`

We originally found the issue with the `store.shopware.com/netinextexportonevent`-plugin.

The "bad" file (`api-error-config.json`) for looked like this:
```json
[
  "name",
  "eventName"
]
```

**Comment by jankal** [comment]
From my POV, options for solution are:

1. Examining the JSON files based on some sort of schema
2. Only reading files conforming to a certain naming convention (like `de-DE.json` - `{locale}.json`)

Another note: we are unable to read JSON files containing arrays at the top level into any usable structure for snippets - so we could also just ditch those files. (I guess this suggestion a variation of option 1)

What do you think @shyim?

**Comment by shyim** [comment]
I would also say skip files which cannot be read and add a info log. based on locale like sounds good.

https://github.com/shopware/shopware/blob/trunk/src/Administration/Snippet/SnippetFinder.php that's btw the PHP parts which searches the snippet files
