### ISSUE TITLE
Watcher breaks when it bumps on a ~scss/variables import

### ISSUE THREAD

**Issue by JolanDeNef** [FriendsOfShopware/shopware-cli#50]
### PHP Version

8.0.0

### Shopware Version

6.4.11.1

### Actual behaviour

Tested the watcher on a plugin with the ~scss/variables import: 

`file: "_file_.scss", context: "@import \"~scss/variables\";\n": Can't find stylesheet to import.`

This import is used for using the variables in Shopping Experience blocks (previews).

### Expected behaviour

The import is recognised by the watcher and compiles without breaking

### Steps to Reproduce?

`shopware-cli extension admin-watch _PluginDirectory_ http://localhost`

Tested the watcher on a plugin that includes an scss file with a ~scss/variables import

**Comment by shyim** [comment]
I guess we can copy that file over and so it still works.

I created also a ticket to get rid of that file as it should be css variables. Importing stuff from admin is not so good
https://issues.shopware.com/issues/NEXT-22302

**Comment by shyim** [comment]
Is fixed with https://github.com/FriendsOfShopware/shopware-cli/commit/6a6f18164f2f9eec6c928cf7dbb9ad06864dc26a
I have tagged 0.1.31 should be available in 10 min
