### ISSUE TITLE
[project dump] Triggers are not dumped

### ISSUE THREAD

**Issue by SvenHerrmann** [FriendsOfShopware/shopware-cli#53]
### PHP Version

8.0

### Shopware Version

6.4.12.0

### Actual behaviour

When dumping a SW6 database, the triggers present in the database are not in the resulting dump.sql.

### Expected behaviour

Triggers should also be dumped to dump.sql

### Steps to Reproduce?

- create a trigger in your database
- dump the database

**Comment by shyim** [comment]
connected to: https://github.com/doutorfinancas/go-mad/issues/38
