### ISSUE TITLE
validate: Ensure running in the correct PHP version / multiple versions

### ISSUE THREAD

**Issue by amenk** [FriendsOfShopware/shopware-cli#54]
### Please describe the feature you would like to see implemented.

I think extensions for 6.4 should be compatible with PHP7.4 - 8.1.

I was running a validate on 8.0 but it failed in the store which seems to check with PHP7.4.

It would be nice if the CLI uses different PHP versions for validation or shows a message, that you should use a different PHP runtime.

What do you think?

**Comment by amenk** [comment]
The store seems to check even for 7.2 compat even the extension is for 6.4 ?

**Comment by shyim** [comment]
The problem is that we use what the user has. 
Maybe a solution could be to spawn up an AWS Lambda which contains PHP 7.4 only and validates the send zip 🤔

**Comment by amenk** [comment]
Yeah ;-)
Or just leave it to the store to validate ...

**Comment by shyim** [comment]
We could try https://github.com/VKCOM/php-parser

**Comment by amenk** [comment]
:open_mouth:

**Comment by shyim** [comment]
so needs now just integrated here https://github.com/FriendsOfShopware/aws-php-syntax-checker-lambda

**Comment by amenk** [comment]
Wow, crazy approach, I like that :-)
Maybe we should add an remark in the README, that the code is sent to an external service? One might expect that everything is happening locally.

**Comment by shyim** [comment]
![image](https://user-images.githubusercontent.com/6224096/195063277-f95d98cf-f924-467e-a2df-7b79ba52d9dc.png)
I will add it to the docs too.

When the API connection fails, it will be an warning

**Comment by shyim** [comment]
I repacked a separate zip and send **only** files ending with `.php` to the service. So not all :sweat_smile:
