### ISSUE TITLE
Add a way to find easily the latest release

### ISSUE THREAD

**Issue by HOSTED-POWER** [FriendsOfShopware/shopware-cli#56]
### Please describe the feature you would like to see implemented.

Hi,

For automation purposes, we would very much like a sort of latest tag.

Now we need to manually pick a version here: https://github.com/FriendsOfShopware/shopware-cli/releases/

It would be nice to have something available like:

https://github.com/FriendsOfShopware/shopware-cli/releases/download/latest/shopware-cli_latest_linux_amd64.deb

Any other means to find the latest release are welcome :)

**Comment by HOSTED-POWER** [comment]
Found this which can help: https://api.github.com/repos/FriendsOfShopware/shopware-cli/releases/latest

Anyone can think of an even easier way perhaps? :)

**Comment by shyim** [comment]
Does one of the other tools not work for you?

https://sw-cli.fos.gg/install/ 🤔 


We could also modifty the template https://goreleaser.com/customization/archive/?h=archives

**Comment by HOSTED-POWER** [comment]
Wow, thanks a lot!!

What exactly was changed? Will this affect the releases page on  https://github.com/FriendsOfShopware/shopware-cli/releases/ ? :)

**Comment by shyim** [comment]
Yes. the next tagged release does not have a version anymore in the filename

**Comment by shyim** [comment]
after https://github.com/FriendsOfShopware/shopware-cli/actions/runs/3226130954 the version number should be away

**Comment by HOSTED-POWER** [comment]
Ok , I tried, but I couldn't find a direct link to for example the latest debian installer package? :)

**Comment by HOSTED-POWER** [comment]
PS: With the new latest, the version numbers even came back, for example:

shopware-cli_0.1.42_linux_amd64.deb

**Comment by shyim** [comment]
It does not work for debian based one :(

The APT repository get's fucked up. Maybe you just want to use the APT repo? https://sw-cli.fos.gg/install/#debianubuntu-apt-based-linux
