### ISSUE TITLE
Plugin upload

### ISSUE THREAD

**Issue by TobiasGraml11** [FriendsOfShopware/shopware-cli#89]
### Please describe the feature you would like to see implemented.

The abandoned plugin uploader had an upload command for the plugin, which we use in a release workflow: https://github.com/FriendsOfShopware/FroshPluginUploader#extupload

Will this also be added to the CLI?

**Comment by shyim** [comment]
Was not documented 🙈 
It should be now https://github.com/FriendsOfShopware/shopware-cli/commit/29101b535e1e358b4a353afcd5e1ff97c9dd5a69

**Comment by TobiasGraml11** [comment]
@shyim Thanks for the quick response!
