### ISSUE TITLE
Validation command does not show same errors as check on upload

### ISSUE THREAD

**Issue by TobiasGraml11** [FriendsOfShopware/shopware-cli#90]
### PHP Version

7.4

### Actual behaviour

1. The automatic code review finds a parsing error, which the validation command does not find.
2. The automatic code review mentions missing `shopware/core` package, which is removed during the creation of the zip file

![image](https://user-images.githubusercontent.com/51320851/207059905-fbc07327-1eb2-4268-a3d5-ebb892898e5d.png)

![image](https://user-images.githubusercontent.com/51320851/207060395-ba662b53-f462-4b93-8adc-65cb8aad5b99.png)

### Expected behaviour

1. Either:
    - The error in the code review is not valid and can be ignored
    - The error should be shown during validation
2. The `require` is not removed during the creation of the zip file

### Steps to Reproduce?

1. Clone repository: https://github.com/findologic/plugin-shopware-6 (develop branch)
2. Add required shopware requirement to `composer.json` (usually done during build process)
    - `"shopware/core": "^6.4.6"`
3. `shopware-cli extension validate plugin-shopware-6`
4. `shopware-cli extension zip plugin-shopware-6`
5.  Not sure how you can check the automatic code review, I uploaded it as new version

**Comment by TobiasGraml11** [comment]
@shyim As we discussed this further on Slack, can this be closed now?

**Comment by shyim** [comment]
After rethinking yes we can close it
