### ISSUE TITLE
Remove secret when packing an app

### ISSUE THREAD

**Issue by wannevancamp** [FriendsOfShopware/shopware-cli#99]
### Please describe the feature you would like to see implemented.

As mentioned in the docs you should never publish the app-secret. I'm wondering if it's a good idea to automatically remove the `<secret>` tag in the `manifest.xml` file when packing an app?

Before packing
```
<setup>
        <registrationUrl>https://my.example.com/registration</registrationUrl>
        <secret>xxxxx-xxxxx-xxxxx-xxxxx</secret>
</setup>
```

After packing
```
<setup>
        <registrationUrl>https://my.example.com/registration</registrationUrl>
</setup>
```

Reference: https://developer.shopware.com/docs/guides/plugins/apps/app-base-guide#registration-response
![image](https://user-images.githubusercontent.com/3399877/213676042-fc6a9b12-ebf1-4a09-9d3b-c8d3729f30fc.png)

**Comment by shyim** [comment]
We need a flag like `--release`, It can be intended to have this packaged because maybe you want to test it on an external system.
